### ISSUE TITLE
it says only owner can add

### ISSUE THREAD

**Issue by Shubh69** [EmoteCollector/bot#83]

**Comment by thehatkid** [comment]
Because owner said that:

> I am no longer interested in developing, maintaining, or hosting Discord bots, nor improving the experience of using Discord.
> On January 20th, :em: and :ec: will be made "private". This means you will not be able to add them to new servers.

See full message: https://discord.com/channels/410627685589450752/412008459253579777/787125939309510666

**Comment by circuitsacul** [comment]
@thehatkid I can't access that link, could you provide an invite to the server it is in?

**Comment by thehatkid** [comment]
@CircuitSacul

> I can't access that link, could you provide an invite to the server it is in?

Bot cannot be invited in other servers, but You can interact with bot in support discord server
Temporary Invite Link: https://discord.gg/GRhCuNx
